---
- name: Configure SWEAGLE taskrunner application.yml
  template:
    src: "{{ sweagle_version }}/taskrunner-application.yml.j2"
    dest: "{{ sweagle_installation_folder }}/bin/taskRunner/application.yml"
  tags: [ sweagle, sweagle-taskrunner ]

- name: "Find taskrunner Jar file"
  find:
    paths: "{{ sweagle_installation_folder }}/bin/taskRunner"
    patterns: "task-run*.jar"
    file_type: "file"
  register: jar_files
  tags: [ sweagle, sweagle-taskrunner ]

- name: Display service creation command
  debug:
    msg: "{{ sweagle_installation_folder }}/scripts/createService_v2.sh sweagleTaskRunner {{ sweagle_installation_folder }}/bin/taskRunner {{ jar_files.files[0].path | basename }} {{ jdk_install_dir }}/bin/java {{ sweagle_taskrunner_xmx }}"
  when: sweagle_create_services
  tags: [ sweagle, sweagle-taskrunner ]

- name: Create service taskrunner
  shell: "{{ sweagle_installation_folder }}/scripts/createService_v2.sh sweagleTaskRunner {{ sweagle_installation_folder }}/bin/taskRunner {{ jar_files.files[0].path | basename }} {{ jdk_install_dir }}/bin/java {{ sweagle_taskrunner_xmx }}"
  become: true
  when: sweagle_create_services
  tags: [ sweagle, sweagle-taskrunner ]

- name: Enable and start taskrunner service
  service:
    name: "sweagleTaskRunner"
    state: started
    enabled: yes
  become: true
  when: sweagle_create_services
  tags: [ sweagle, sweagle-taskrunner ]

- name: Wait for taskrunner to startup
  wait_for: host="{{ inventory_hostname }}" port={{ sweagle_taskrunner_port }} delay=15 connect_timeout=5 timeout=120
  when: sweagle_create_services
  tags: [ sweagle, sweagle-taskrunner ]
